/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_project;

import Classes.Amenities;
import Classes.Category;
import java.awt.Color;
import java.awt.Cursor;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ARORA
 */
public class Form_Amenities extends javax.swing.JFrame {

    /**
     * Creates new form Form_Amenities
     */
    
    Amenities ame = new Amenities();
    Category category = new Category();
    HashMap<String, Integer> map = category.categoryHashMap();
    
    public Form_Amenities() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        ButtonGroup btn_grp = new ButtonGroup();
        btn_grp.add(jRadioButton_granite);
        btn_grp.add(jRadioButton_marble);
        
        populateComboBoxCategory();
                
    }
    
    
    public void populateComboBoxCategory()
    { 
        
        for(String s: map.keySet())
        { 
            jComboBox_layout.addItem(s);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_close = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_Id = new javax.swing.JSpinner();
        jButton_Add_House_ = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jLabel_imagePath = new javax.swing.JLabel();
        jButton_Reset_ = new javax.swing.JButton();
        jButton_Add_Images_ = new javax.swing.JButton();
        jComboBox_layout = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_vastuu = new javax.swing.JComboBox<>();
        jComboBox_area = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_club_house = new javax.swing.JComboBox<>();
        jTextField_rent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox_air_cond = new javax.swing.JCheckBox();
        jCheckBox_wifi = new javax.swing.JCheckBox();
        jCheckBox_balcony = new javax.swing.JCheckBox();
        jCheckBox_modular_kitchen = new javax.swing.JCheckBox();
        jCheckBox_parking = new javax.swing.JCheckBox();
        jCheckBox_furniture = new javax.swing.JCheckBox();
        jCheckBox_security = new javax.swing.JCheckBox();
        jCheckBox_lift = new javax.swing.JCheckBox();
        jButton_Category_List_ = new javax.swing.JButton();
        jButton_Amenities_List_ = new javax.swing.JButton();
        jComboBox_vicinity = new javax.swing.JComboBox<>();
        jRadioButton_granite = new javax.swing.JRadioButton();
        jRadioButton_marble = new javax.swing.JRadioButton();
        jButton_Search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jPanel3.setBackground(new java.awt.Color(225, 112, 85));
        jPanel3.setToolTipText("");

        jLabel_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amenities");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(471, 471, 471)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_close))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("House ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Layout:");

        jSpinner_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton_Add_House_.setBackground(new java.awt.Color(102, 255, 102));
        jButton_Add_House_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Add_House_.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Add_House_.setText("Add");
        jButton_Add_House_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_House_ActionPerformed(evt);
            }
        });

        jButton_Edit.setBackground(new java.awt.Color(29, 209, 161));
        jButton_Edit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Edit.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Remove.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Remove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Remove.setText("Remove");
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });

        jLabel_imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_imagePath.setText("     ");

        jButton_Reset_.setBackground(new java.awt.Color(255, 153, 51));
        jButton_Reset_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Reset_.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Reset_.setText("Reset");
        jButton_Reset_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Reset_ActionPerformed(evt);
            }
        });

        jButton_Add_Images_.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Add_Images_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Add_Images_.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Add_Images_.setText("Add House Images");
        jButton_Add_Images_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_Images_ActionPerformed(evt);
            }
        });

        jComboBox_layout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_layout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_layoutActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Vicinity:");

        jComboBox_vastuu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_vastuu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North Facing", "South Facing", "West Facing", "East Facing" }));

        jComboBox_area.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "400 - 600", "600 - 800", "800 - 1000", "> 1000" }));
        jComboBox_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_areaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Area of plot:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Flooring:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Club House:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Vastuu:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Expected Rent/month:");

        jComboBox_club_house.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_club_house.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming Pool", "Gym", "Badminton" }));
        jComboBox_club_house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_club_houseActionPerformed(evt);
            }
        });

        jTextField_rent.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jTextField_rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rentActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Specifications");

        jPanel4.setBackground(new java.awt.Color(219, 228, 219));

        jCheckBox_air_cond.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_air_cond.setText("Air Conditioning");

        jCheckBox_wifi.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_wifi.setText("Wifi");
        jCheckBox_wifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_wifiActionPerformed(evt);
            }
        });

        jCheckBox_balcony.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_balcony.setText("Balcony");

        jCheckBox_modular_kitchen.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_modular_kitchen.setText("Modular Kitchen");

        jCheckBox_parking.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_parking.setText("Parking");

        jCheckBox_furniture.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_furniture.setText("Furniture");

        jCheckBox_security.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_security.setText("Security");

        jCheckBox_lift.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jCheckBox_lift.setText("Lift");
        jCheckBox_lift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_liftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_wifi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_air_cond, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_modular_kitchen))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_furniture, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_parking, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_lift, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_security, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_air_cond)
                    .addComponent(jCheckBox_balcony)
                    .addComponent(jCheckBox_furniture)
                    .addComponent(jCheckBox_security))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_lift)
                            .addComponent(jCheckBox_parking)
                            .addComponent(jCheckBox_modular_kitchen)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_wifi)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButton_Category_List_.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Category_List_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Category_List_.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Category_List_.setText("Category List");
        jButton_Category_List_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Category_List_ActionPerformed(evt);
            }
        });

        jButton_Amenities_List_.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Amenities_List_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Amenities_List_.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Amenities_List_.setText("Amenities List & Booking");
        jButton_Amenities_List_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Amenities_List_ActionPerformed(evt);
            }
        });

        jComboBox_vicinity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_vicinity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mall", "School", "Restaurant", "Railway Station", "Air Port", "Hospital" }));
        jComboBox_vicinity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_vicinityActionPerformed(evt);
            }
        });

        jRadioButton_granite.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jRadioButton_granite.setText("granite");

        jRadioButton_marble.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jRadioButton_marble.setText("marble");

        jButton_Search.setBackground(new java.awt.Color(0, 0, 153));
        jButton_Search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_layout, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox_vicinity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Add_House_, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jButton_Remove)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Reset_, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButton_Amenities_List_))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jButton_Add_Images_, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSpinner_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Search)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_club_house, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_area, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton_marble, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_granite, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox_vastuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Category_List_, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_area, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Search)
                    .addComponent(jSpinner_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton_Add_House_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_layout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox_vicinity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_club_house, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Reset_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jRadioButton_marble)
                            .addComponent(jRadioButton_granite))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTextField_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jComboBox_vastuu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton_Add_Images_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Category_List_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Amenities_List_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1476, 1476, 1476)
                .addComponent(jLabel_imagePath)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        jLabel_close.setForeground(Color.RED);
        jLabel_close.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        jLabel_close.setForeground(Color.BLACK);
        jLabel_close.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jButton_Add_House_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_House_ActionPerformed
        //add a new brand
       int id = (int)jSpinner_Id.getValue(); 
       String layout = jComboBox_layout.getSelectedItem().toString();
       String vicinity = jComboBox_vicinity.getSelectedItem().toString();
       String rent = jTextField_rent.getText(); // Assuming jTextField_rent is your text field for rent input
       String area = jComboBox_area.getSelectedItem().toString();
       String flooring = "granite";
       String club_house = jComboBox_club_house.getSelectedItem().toString();
       String vastuu = jComboBox_vastuu.getSelectedItem().toString();
       
       String air_cond = "no";
       String wifi = "no";
       String lift = "no";
       String parking = "no";
       String security = "no";
       String modular_kitchen = "no";
       String balcony ="no";
       String furniture = "no";
       
       if(jRadioButton_marble.isSelected())
       { 
           flooring = "marble";
       }
       if(jCheckBox_air_cond.isSelected())
       { 
           air_cond = "yes";
       }
       if(jCheckBox_wifi.isSelected())
       { 
           wifi = "yes";
       }
       if(jCheckBox_balcony.isSelected())
       { 
           balcony = "yes";
       }
       if(jCheckBox_furniture.isSelected())
       { 
           furniture = "yes";
       }
       if(jCheckBox_modular_kitchen.isSelected())
       { 
           modular_kitchen = "yes";
       }
       if(jCheckBox_parking.isSelected())
       { 
           parking = "yes";
       }
       if(jCheckBox_lift.isSelected())
       { 
           lift = "yes";
       }
       if(jCheckBox_security.isSelected())
       { 
           security = "yes";
       }
       
       
       ame.addAmenities(layout, vicinity, rent, area, flooring,club_house, vastuu, air_cond, wifi,balcony,lift,parking,security,modular_kitchen,furniture);
      
       

    }//GEN-LAST:event_jButton_Add_House_ActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed

       int id = (int)jSpinner_Id.getValue();
       String layout = jComboBox_layout.getSelectedItem().toString();
       String vicinity = jComboBox_vicinity.getSelectedItem().toString();
       String rent = jTextField_rent.getText(); // Assuming jTextField_rent is your text field for rent input
       String area = jComboBox_area.getSelectedItem().toString();
       String flooring = "granite";
       String club_house = jComboBox_club_house.getSelectedItem().toString();
       String vastuu = jComboBox_vastuu.getSelectedItem().toString();
       
       String air_cond = "no";
       String wifi = "no";
       String lift = "no";
       String parking = "no";
       String security = "no";
       String modular_kitchen = "no";
       String balcony ="no";
       String furniture = "no";
       
       if(jRadioButton_marble.isSelected())
       { 
           flooring = "marble";
       }
       if(jCheckBox_air_cond.isSelected())
       { 
           air_cond = "yes";
       }
       if(jCheckBox_wifi.isSelected())
       { 
           wifi = "yes";
       }
       if(jCheckBox_balcony.isSelected())
       { 
           balcony = "yes";
       }
       if(jCheckBox_furniture.isSelected())
       { 
           furniture = "yes";
       }
       if(jCheckBox_modular_kitchen.isSelected())
       { 
           modular_kitchen = "yes";
       }
       if(jCheckBox_parking.isSelected())
       { 
           parking = "yes";
       }
       if(jCheckBox_lift.isSelected())
       { 
           lift = "yes";
       }
       if(jCheckBox_security.isSelected())
       { 
           security = "yes";
       }
       
       
       ame.editAmenities( id, layout, vicinity, rent, area, flooring,club_house, vastuu, air_cond, wifi,balcony,lift,parking,security,modular_kitchen,furniture);
      
       
        

    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed

        int id = (int)jSpinner_Id.getValue();
      
        
         int confirm = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this house?","Confirm",JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION)
        { 
           
              ame.removeAmenities(id);
        }
        
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    private void jButton_Reset_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Reset_ActionPerformed

       /* populateJtableWithLocations();*/
       jComboBox_layout.setSelectedIndex(0);
    
        jComboBox_vicinity.setSelectedIndex(0);
        jTextField_rent.setText("");
        jComboBox_area.setSelectedIndex(0);
        jComboBox_club_house.setSelectedIndex(0);
        jComboBox_vastuu.setSelectedIndex(0);
        jRadioButton_granite.setSelected(false);
        jRadioButton_marble.setSelected(false);
        
        jCheckBox_air_cond.setSelected(false);
        jCheckBox_wifi.setSelected(false);
         jCheckBox_balcony.setSelected(false);
           jCheckBox_parking.setSelected(false);
            jCheckBox_lift.setSelected(false);
             jCheckBox_security.setSelected(false);
              jCheckBox_modular_kitchen.setSelected(false);
               jCheckBox_furniture.setSelected(false);
       

    }//GEN-LAST:event_jButton_Reset_ActionPerformed

    private void jButton_Add_Images_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_Images_ActionPerformed
         Form_HouseImages frm_houseimg = new Form_HouseImages();
         frm_houseimg.setVisible(true);
    }//GEN-LAST:event_jButton_Add_Images_ActionPerformed

    private void jTextField_rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rentActionPerformed

    private void jComboBox_club_houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_club_houseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_club_houseActionPerformed

    private void jCheckBox_wifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_wifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_wifiActionPerformed

    private void jCheckBox_liftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_liftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_liftActionPerformed

    private void jButton_Category_List_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Category_List_ActionPerformed

            Form_CategoryList frm_ctglist = new Form_CategoryList();
                    frm_ctglist.setVisible(true);
    }//GEN-LAST:event_jButton_Category_List_ActionPerformed

    private void jButton_Amenities_List_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Amenities_List_ActionPerformed
         Form_AmenitiesList frm_amelist = new Form_AmenitiesList();
         frm_amelist.setVisible(true);
         
    }//GEN-LAST:event_jButton_Amenities_List_ActionPerformed

    private void jComboBox_vicinityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_vicinityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_vicinityActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        int house_id = (int) jSpinner_Id.getValue();
        Amenities new_amenities = ame.getAmenitiesById(house_id);
        
        jButton_Reset_ActionPerformed(null);
        
        if(new_amenities != null)
        { 
            jComboBox_layout.setSelectedItem(new_amenities.getLayout());
             jComboBox_vicinity.setSelectedItem(new_amenities.getVicinity());
             jTextField_rent.setText(new_amenities.getRent());
             jComboBox_area.setSelectedItem(new_amenities.getArea());
             jComboBox_vastuu.setSelectedItem(new_amenities.getVastuu());
             jComboBox_club_house.setSelectedItem(new_amenities.getClub_house());
             
             if(new_amenities.getFlooring().equals("marble"))
             { 
                 jRadioButton_marble.setSelected(true);
                 
             }
             System.out.println(new_amenities.getFlooring());
             
             if(new_amenities.getAir_con().equals("yes"))
             { 
                 jCheckBox_air_cond.setSelected(true);
             }
             if(new_amenities.getWifi().equals("yes"))
             { 
                 jCheckBox_wifi.setSelected(true);
             }
             if(new_amenities.getLift().equals("yes"))
             { 
                 jCheckBox_lift.setSelected(true);
             }
             if(new_amenities.getBalcony().equals("yes"))
             { 
                 jCheckBox_balcony.setSelected(true);
             }
             if(new_amenities.getParking().equals("yes"))
             { 
                 jCheckBox_parking.setSelected(true);
             }
             if(new_amenities.getSecurity().equals("yes"))
             { 
                 jCheckBox_security.setSelected(true);
             }
             if(new_amenities.getFur().equals("yes"))
             { 
                 jCheckBox_furniture.setSelected(true);
             }
             if(new_amenities.getMod_kitch().equals("yes"))
             { 
                 jCheckBox_modular_kitchen.setSelected(true);
             }
             
             
             
        }
        
        
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jComboBox_layoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_layoutActionPerformed
        int category_id = 0;
        for(Map.Entry<String,Integer> entry : map.entrySet())
        {
            if(entry.getValue().equals(jComboBox_layout.getSelectedItem().toString()))
            {
                category_id =  entry.getValue();
            }
        }
    }//GEN-LAST:event_jComboBox_layoutActionPerformed

    private void jComboBox_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_areaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Amenities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_House_;
    private javax.swing.JButton jButton_Add_Images_;
    private javax.swing.JButton jButton_Amenities_List_;
    private javax.swing.JButton jButton_Category_List_;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JButton jButton_Reset_;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JCheckBox jCheckBox_air_cond;
    private javax.swing.JCheckBox jCheckBox_balcony;
    private javax.swing.JCheckBox jCheckBox_furniture;
    private javax.swing.JCheckBox jCheckBox_lift;
    private javax.swing.JCheckBox jCheckBox_modular_kitchen;
    private javax.swing.JCheckBox jCheckBox_parking;
    private javax.swing.JCheckBox jCheckBox_security;
    private javax.swing.JCheckBox jCheckBox_wifi;
    private javax.swing.JComboBox<String> jComboBox_area;
    private javax.swing.JComboBox<String> jComboBox_club_house;
    private javax.swing.JComboBox<String> jComboBox_layout;
    private javax.swing.JComboBox<String> jComboBox_vastuu;
    private javax.swing.JComboBox<String> jComboBox_vicinity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_imagePath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_granite;
    private javax.swing.JRadioButton jRadioButton_marble;
    private javax.swing.JSpinner jSpinner_Id;
    private javax.swing.JTextField jTextField_rent;
    // End of variables declaration//GEN-END:variables
}
