/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_project;

import Classes.Amenities;
import Classes.Amenities.HouseImage;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
//import Houses.*;

/**
 *
 * @author ARORA
 */
public class Form_HouseImages extends javax.swing.JFrame {

    /**
     * Creates new form Form_HouseImages
     */
    Amenities amen = new Amenities();
    ArrayList<Amenities> housesList = amen.housesList(); 
    ArrayList<Amenities.HouseImage> houseImages;
    public Form_HouseImages() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        populateJtableWithHouses();
    }
    
    
    public void displayImage(int width,int height,String image_path, JLabel label)
    { 
        ImageIcon imageIco = new ImageIcon(image_path);
        Image image = imageIco.getImage().getScaledInstance(width,height, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(image));
    }
    
    public void displayByteImage(int width,int height,byte[] image_byte, JLabel label)
    { 
        ImageIcon imageIco = new ImageIcon(image_byte);
        Image image = imageIco.getImage().getScaledInstance(width,height, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(image));
    }
    
    public String selectImage()
    { 
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Picture");
        
        fileChooser.setCurrentDirectory(new File("C:\\images"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("image", ".png", ".jpg");
        fileChooser.addChoosableFileFilter(filter);
        
        int state = fileChooser.showSaveDialog(null);
        String path = "";
        if(state == JFileChooser.APPROVE_OPTION)
        { 
            path = fileChooser.getSelectedFile().getAbsolutePath();
        }
        
        return path;
    }
    
    public void populateJtableWithHouses()
    {
        //jtable columns
        String[] columnsName = {"ID","Layout","Rent/month"};
        
        //jtable rows
        Object[][] rows = new Object[housesList.size()][columnsName.length];
        
        for(int i=0;i<housesList.size();i++)
        {
            rows[i][0] = housesList.get(i).getId();
            rows[i][1] = housesList.get(i).getLayout();
            rows[i][2] = housesList.get(i).getRent();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        jTable_Houses.setModel(model);
        
    }
    
    public void populateJtableWithHouseImages(int house_id)
    {
        ArrayList<HouseImage> imagesList = amen.houseImagesList(house_id);
        //jtable columns
        String[] columnsName = {"Image ID"};
        
        //jtable rows
        Object[][] rows = new Object[imagesList.size()][columnsName.length];
        
        for(int i=0;i<imagesList.size();i++)
        {
            rows[i][0] = imagesList.get(i);
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        jTable_House_Images.setModel(model);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_close = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Houses = new javax.swing.JTable();
        jLabel_imagePath = new javax.swing.JLabel();
        jLabel_House_Pics = new javax.swing.JLabel();
        jButton_Select_Image = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_House_Images = new javax.swing.JTable();
        jButton_Add_Image = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Remove_Image1 = new javax.swing.JButton();
        jLabel_imagePath_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jPanel3.setBackground(new java.awt.Color(225, 112, 85));
        jPanel3.setToolTipText("");

        jLabel_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("House Images");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(480, 480, 480)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTable_Houses.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable_Houses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Houses.setRowHeight(50);
        jTable_Houses.setSelectionBackground(new java.awt.Color(255, 51, 0));
        jTable_Houses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_HousesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Houses);

        jLabel_imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_imagePath.setText("     ");

        jLabel_House_Pics.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_House_Pics.setOpaque(true);

        jButton_Select_Image.setBackground(new java.awt.Color(51, 102, 255));
        jButton_Select_Image.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Select_Image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Select_Image.setText("Select Image");
        jButton_Select_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_ImageActionPerformed(evt);
            }
        });

        jTable_House_Images.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable_House_Images.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_House_Images.setRowHeight(40);
        jTable_House_Images.setSelectionBackground(new java.awt.Color(255, 51, 0));
        jTable_House_Images.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_House_ImagesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_House_Images);

        jButton_Add_Image.setBackground(new java.awt.Color(255, 102, 0));
        jButton_Add_Image.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Add_Image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Image.setText("Add Image");
        jButton_Add_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ImageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setText("Houses");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel2.setText("Selected House Images");

        jButton_Remove_Image1.setBackground(new java.awt.Color(0, 153, 0));
        jButton_Remove_Image1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Remove_Image1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Image1.setText("Remove Image");
        jButton_Remove_Image1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_Image1ActionPerformed(evt);
            }
        });

        jLabel_imagePath_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_imagePath_1.setText("############");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_Add_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Select_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Remove_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_imagePath_1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_House_Pics, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel_House_Pics, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_imagePath_1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_Select_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Add_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Remove_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(624, 624, 624)
                        .addComponent(jLabel_imagePath)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        jLabel_close.setForeground(Color.RED);
        jLabel_close.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        jLabel_close.setForeground(Color.BLACK);
        jLabel_close.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jTable_HousesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_HousesMouseClicked
        int index = jTable_Houses.getSelectedRow();
        int house_id = Integer.valueOf(jTable_Houses.getValueAt(index, 0).toString());
        //System.out.println(house_id);
        populateJtableWithHouseImages(house_id);
        houseImages = amen.houseImagesList(house_id);
    }//GEN-LAST:event_jTable_HousesMouseClicked

    private void jTable_House_ImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_House_ImagesMouseClicked
        // display the selected image
            //jLabel_House_Pics.setIcon(null);
            int index = jTable_Houses.getSelectedRow();
           // System.out.println("index ->" + index);
            int house_id = Integer.valueOf(jTable_Houses.getValueAt(index, 0).toString());
           // System.out.println("Image_id ->" + house_id);
            byte[] img = null;
            for(Amenities.HouseImage himg: houseImages)
            { 
                if(himg.getImg_id() == house_id)
                { 
                    img = himg.getHouse_img();
                }
            }
            //it should be image_id
            displayByteImage(jLabel_House_Pics.getWidth(), jLabel_House_Pics.getHeight(), img, jLabel_House_Pics);
    }//GEN-LAST:event_jTable_House_ImagesMouseClicked

    private void jButton_Add_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ImageActionPerformed
        //add an image
        try {
            int index = jTable_Houses.getSelectedRow();
            int house_id = Integer.valueOf(jTable_Houses.getValueAt(index, 0).toString());
        byte[] image = Files.readAllBytes(Paths.get(jLabel_imagePath_1.getText()));
        
            System.out.println(house_id);
            amen.addHouseImage(house_id, image);
               
    } catch(IOException ex) {
        
        JOptionPane.showMessageDialog(null,"Select An Image [" +  ex + "]","House Image", 2);
        java.util.logging.Logger.getLogger(Form_HouseImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton_Add_ImageActionPerformed

    private void jButton_Select_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_ImageActionPerformed
        // browse and display image
        String imagePath = selectImage();
        displayImage(jLabel_House_Pics.getWidth(), jLabel_House_Pics.getHeight(), imagePath, jLabel_House_Pics);
        
        jLabel_imagePath_1.setText(imagePath);
    }//GEN-LAST:event_jButton_Select_ImageActionPerformed

    private void jButton_Remove_Image1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_Image1ActionPerformed
        // TODO add your handling code here:
        try
        { 
            int index = jTable_House_Images.getSelectedRow();
            int image_id = Integer.valueOf(jTable_House_Images.getValueAt(index,0).toString());
            amen.removeHouseImage(image_id);
            int confirm = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this house image  ?","Confirm",JOptionPane.YES_NO_OPTION);
        
            if(confirm == JOptionPane.YES_OPTION)
            { 
           
               amen.removeHouseImage(image_id);
              
            }
        }
         catch(Exception ex)
        { 
            JOptionPane.showMessageDialog(null,"Select the image first","Delete Image",2);
        }
        
        
        
    }//GEN-LAST:event_jButton_Remove_Image1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_HouseImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_HouseImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_HouseImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_HouseImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_HouseImages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Image;
    private javax.swing.JButton jButton_Remove_Image1;
    private javax.swing.JButton jButton_Select_Image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_House_Pics;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_imagePath;
    private javax.swing.JLabel jLabel_imagePath_1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_House_Images;
    private javax.swing.JTable jTable_Houses;
    // End of variables declaration//GEN-END:variables
}
